import { CountryType } from "@/types/user";
import {
  Add as AddIcon,
  BuildRounded,
  Dashboard,
  EmojiEvents,
  Gavel,
  ErrorOutlined as ModerationIcon,
  People,
  PersonSharp,
  AttachMoney as RevenueIcon,
  RemoveRedEye as ViewsIcon,
  Poll as VotesIcon
} from "@mui/icons-material";
import { UserStatus, VOTING_PERIOD_TYPE } from "./enum";

export const STATS = [
  {
    label: "Entries",
    value: "43",
    subtitle: "VIEW ENTRIES",
    icon: <AddIcon sx={{ fontSize: 32 }} />,
    color: "#e2e8f0",
  },
  {
    label: "Needs moderation",
    value: "2",
    subtitle: "VIEW ENTRIES",
    icon: <ModerationIcon sx={{ fontSize: 32 }} />,
    color: "#fef3c7",
  },
  {
    label: "Views",
    value: "84",
    subtitle: "VIEW MORE",
    icon: <ViewsIcon sx={{ fontSize: 32 }} />,
    color: "#d1fae5",
  },
  {
    label: "Votes",
    value: "0",
    subtitle: "VIEW RANKING",
    icon: <VotesIcon sx={{ fontSize: 32 }} />,
    color: "#dbeafe",
  },
  {
    label: "Entry Revenue (USD)",
    value: "$ 0",
    subtitle: "VIEW ENTRY TRANSACTIONS",
    icon: <RevenueIcon sx={{ fontSize: 32 }} />,
    color: "#f3e8ff",
  },
  {
    label: "Vote Revenue (USD)",
    value: "$ 0",
    subtitle: "VIEW VOTE TRANSACTIONS",
    icon: <RevenueIcon sx={{ fontSize: 32 }} />,
    color: "#ffedd5",
  },
];

export const ENTRIES = [
  {
    id: 1,
    contest_Id: "contest-uuid-1",
    title: "Current of Consequences",
    score: 0,
    uploaded: "2026-03-06 13:18:26",
    author: "Oindrila Chakraborty",
    thumbnail:
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=100&h=60&fit=crop",
  },
  {
    id: 2,
    contest_Id: "contest-uuid-2",
    title: "test",
    score: 0,
    uploaded: "2026-03-05 03:04:54",
    author: "Anshumaan mishra",
    thumbnail:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=100&h=60&fit=crop",
  },
  {
    id: 3,
    contest_Id: "contest-uuid-3",
    title: "Revolt AI - REVOLUTIONIZING EV BATTERY LIFE WITH AI",
    score: 0,
    uploaded: "2026-03-01 04:21:05",
    author: "Jeremy Robin",
    thumbnail:
      "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=100&h=60&fit=crop",
  },
  {
    id: 4,
    contest_Id: "contest-uuid-4",
    title: "Luminora",
    score: 0,
    uploaded: "2026-02-25 10:35:53",
    author: "Oindrila Chakraborty",
    thumbnail:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=100&h=60&fit=crop",
  },
];

export const CONTESTS = [
  {
    id: 1,
    title: "Spring Code Jam",
    status: "Active",
    participants: 156,
  },
  {
    id: 2,
    title: "UI/UX Challenge",
    status: "Upcoming",
    participants: 42,
  },
  {
    id: 3,
    title: "Tech Stack Hackathon",
    status: "Completed",
    participants: 89,
  },
  {
    id: 4,
    title: "AI Innovation Contest",
    status: "Active",
    participants: 210,
  },
];

export const SIDEBAR = [
  {
    label: "Dashboard",
    icon: Dashboard,
    href: "/dashboard",
  },
  {
    label: "User Management",
    subModules: [
      {
        label: "Users",
        icon: People,
        href: "/user-management/users",
      },
      {
        label: "Judges",
        icon: Gavel,
        href: "/user-management/judges",
      },
      {
        label: "Permission Management",
        href: "/user-management/permissions",
        icon: PersonSharp,
      },
    ],
  },
  {
    label: "Contest Management",
    subModules: [
      {
        label: "Contests",
        icon: EmojiEvents,
        href: "/contest-management/contests",
      },
      {
        label: "Form Builder",
        icon: BuildRounded,
        href: "/form-builder",
      },
      // {
      //   label: "Entries",
      //   icon: undefined,
      //   href: "/contest-management/entries",
      // },
    ],
  },
  {},
];

export const STATUS_OPTIONS = [
  UserStatus.ALL,
  UserStatus.ACTIVE,
  UserStatus.INACTIVE,
  UserStatus.BANNED,
  UserStatus.PENDING,
  UserStatus.REJECTED,
];

export const JUDGES_TABLE_HEADER = [
  "Name",
  "Phone number",
  "Expertise",
  "Status",
  "Actions",
];

export const GRADE_OPTIONS = [
  {
    label: "Year 6/Grade 5",
  },
  {
    label: "Year 7/Grade 6",
  },
  {
    label: "Year 8/Grade 7",
  },
  {
    label: "Year 9/Grade 8",
  },
  {
    label: "Year 10/Grade 9",
  },
  {
    label: "Year 11/Grade 10",
  },
  {
    label: "Year 12/Grade 11",
  },
  {
    label: "Year 13/Grade 12",
  },
  {
    label: "Undergraduate",
  },
];

export const countries: readonly CountryType[] = [
  { code: "AD", label: "Andorra", phone: "376" },
  {
    code: "AE",
    label: "United Arab Emirates",
    phone: "971",
  },
  { code: "AF", label: "Afghanistan", phone: "93" },
  {
    code: "AG",
    label: "Antigua and Barbuda",
    phone: "1-268",
  },
  { code: "AI", label: "Anguilla", phone: "1-264" },
  { code: "AL", label: "Albania", phone: "355" },
  { code: "AM", label: "Armenia", phone: "374" },
  { code: "AO", label: "Angola", phone: "244" },
  { code: "AQ", label: "Antarctica", phone: "672" },
  { code: "AR", label: "Argentina", phone: "54" },
  { code: "AS", label: "American Samoa", phone: "1-684" },
  { code: "AT", label: "Austria", phone: "43" },
  {
    code: "AU",
    label: "Australia",
    phone: "61",
    suggested: true,
  },
  { code: "AW", label: "Aruba", phone: "297" },
  { code: "AX", label: "Alland Islands", phone: "358" },
  { code: "AZ", label: "Azerbaijan", phone: "994" },
  {
    code: "BA",
    label: "Bosnia and Herzegovina",
    phone: "387",
  },
  { code: "BB", label: "Barbados", phone: "1-246" },
  { code: "BD", label: "Bangladesh", phone: "880" },
  { code: "BE", label: "Belgium", phone: "32" },
  { code: "BF", label: "Burkina Faso", phone: "226" },
  { code: "BG", label: "Bulgaria", phone: "359" },
  { code: "BH", label: "Bahrain", phone: "973" },
  { code: "BI", label: "Burundi", phone: "257" },
  { code: "BJ", label: "Benin", phone: "229" },
  { code: "BL", label: "Saint Barthelemy", phone: "590" },
  { code: "BM", label: "Bermuda", phone: "1-441" },
  { code: "BN", label: "Brunei Darussalam", phone: "673" },
  { code: "BO", label: "Bolivia", phone: "591" },
  { code: "BR", label: "Brazil", phone: "55" },
  { code: "BS", label: "Bahamas", phone: "1-242" },
  { code: "BT", label: "Bhutan", phone: "975" },
  { code: "BV", label: "Bouvet Island", phone: "47" },
  { code: "BW", label: "Botswana", phone: "267" },
  { code: "BY", label: "Belarus", phone: "375" },
  { code: "BZ", label: "Belize", phone: "501" },
  {
    code: "CA",
    label: "Canada",
    phone: "1",
    suggested: true,
  },
  {
    code: "CC",
    label: "Cocos (Keeling) Islands",
    phone: "61",
  },
  {
    code: "CD",
    label: "Congo, Democratic Republic of the",
    phone: "243",
  },
  {
    code: "CF",
    label: "Central African Republic",
    phone: "236",
  },
  {
    code: "CG",
    label: "Congo, Republic of the",
    phone: "242",
  },
  { code: "CH", label: "Switzerland", phone: "41" },
  { code: "CI", label: "Cote d'Ivoire", phone: "225" },
  { code: "CK", label: "Cook Islands", phone: "682" },
  { code: "CL", label: "Chile", phone: "56" },
  { code: "CM", label: "Cameroon", phone: "237" },
  { code: "CN", label: "China", phone: "86" },
  { code: "CO", label: "Colombia", phone: "57" },
  { code: "CR", label: "Costa Rica", phone: "506" },
  { code: "CU", label: "Cuba", phone: "53" },
  { code: "CV", label: "Cape Verde", phone: "238" },
  { code: "CW", label: "Curacao", phone: "599" },
  { code: "CX", label: "Christmas Island", phone: "61" },
  { code: "CY", label: "Cyprus", phone: "357" },
  { code: "CZ", label: "Czech Republic", phone: "420" },
  {
    code: "DE",
    label: "Germany",
    phone: "49",
    suggested: true,
  },
  { code: "DJ", label: "Djibouti", phone: "253" },
  { code: "DK", label: "Denmark", phone: "45" },
  { code: "DM", label: "Dominica", phone: "1-767" },
  {
    code: "DO",
    label: "Dominican Republic",
    phone: "1-809",
  },
  { code: "DZ", label: "Algeria", phone: "213" },
  { code: "EC", label: "Ecuador", phone: "593" },
  { code: "EE", label: "Estonia", phone: "372" },
  { code: "EG", label: "Egypt", phone: "20" },
  { code: "EH", label: "Western Sahara", phone: "212" },
  { code: "ER", label: "Eritrea", phone: "291" },
  { code: "ES", label: "Spain", phone: "34" },
  { code: "ET", label: "Ethiopia", phone: "251" },
  { code: "FI", label: "Finland", phone: "358" },
  { code: "FJ", label: "Fiji", phone: "679" },
  {
    code: "FK",
    label: "Falkland Islands (Malvinas)",
    phone: "500",
  },
  {
    code: "FM",
    label: "Micronesia, Federated States of",
    phone: "691",
  },
  { code: "FO", label: "Faroe Islands", phone: "298" },
  {
    code: "FR",
    label: "France",
    phone: "33",
    suggested: true,
  },
  { code: "GA", label: "Gabon", phone: "241" },
  { code: "GB", label: "United Kingdom", phone: "44" },
  { code: "GD", label: "Grenada", phone: "1-473" },
  { code: "GE", label: "Georgia", phone: "995" },
  { code: "GF", label: "French Guiana", phone: "594" },
  { code: "GG", label: "Guernsey", phone: "44" },
  { code: "GH", label: "Ghana", phone: "233" },
  { code: "GI", label: "Gibraltar", phone: "350" },
  { code: "GL", label: "Greenland", phone: "299" },
  { code: "GM", label: "Gambia", phone: "220" },
  { code: "GN", label: "Guinea", phone: "224" },
  { code: "GP", label: "Guadeloupe", phone: "590" },
  { code: "GQ", label: "Equatorial Guinea", phone: "240" },
  { code: "GR", label: "Greece", phone: "30" },
  {
    code: "GS",
    label: "South Georgia and the South Sandwich Islands",
    phone: "500",
  },
  { code: "GT", label: "Guatemala", phone: "502" },
  { code: "GU", label: "Guam", phone: "1-671" },
  { code: "GW", label: "Guinea-Bissau", phone: "245" },
  { code: "GY", label: "Guyana", phone: "592" },
  { code: "HK", label: "Hong Kong", phone: "852" },
  {
    code: "HM",
    label: "Heard Island and McDonald Islands",
    phone: "672",
  },
  { code: "HN", label: "Honduras", phone: "504" },
  { code: "HR", label: "Croatia", phone: "385" },
  { code: "HT", label: "Haiti", phone: "509" },
  { code: "HU", label: "Hungary", phone: "36" },
  { code: "ID", label: "Indonesia", phone: "62" },
  { code: "IE", label: "Ireland", phone: "353" },
  { code: "IL", label: "Israel", phone: "972" },
  { code: "IM", label: "Isle of Man", phone: "44" },
  { code: "IN", label: "India", phone: "91" },
  {
    code: "IO",
    label: "British Indian Ocean Territory",
    phone: "246",
  },
  { code: "IQ", label: "Iraq", phone: "964" },
  {
    code: "IR",
    label: "Iran, Islamic Republic of",
    phone: "98",
  },
  { code: "IS", label: "Iceland", phone: "354" },
  { code: "IT", label: "Italy", phone: "39" },
  { code: "JE", label: "Jersey", phone: "44" },
  { code: "JM", label: "Jamaica", phone: "1-876" },
  { code: "JO", label: "Jordan", phone: "962" },
  {
    code: "JP",
    label: "Japan",
    phone: "81",
    suggested: true,
  },
  { code: "KE", label: "Kenya", phone: "254" },
  { code: "KG", label: "Kyrgyzstan", phone: "996" },
  { code: "KH", label: "Cambodia", phone: "855" },
  { code: "KI", label: "Kiribati", phone: "686" },
  { code: "KM", label: "Comoros", phone: "269" },
  {
    code: "KN",
    label: "Saint Kitts and Nevis",
    phone: "1-869",
  },
  {
    code: "KP",
    label: "Korea, Democratic People's Republic of",
    phone: "850",
  },
  { code: "KR", label: "Korea, Republic of", phone: "82" },
  { code: "KW", label: "Kuwait", phone: "965" },
  { code: "KY", label: "Cayman Islands", phone: "1-345" },
  { code: "KZ", label: "Kazakhstan", phone: "7" },
  {
    code: "LA",
    label: "Lao People's Democratic Republic",
    phone: "856",
  },
  { code: "LB", label: "Lebanon", phone: "961" },
  { code: "LC", label: "Saint Lucia", phone: "1-758" },
  { code: "LI", label: "Liechtenstein", phone: "423" },
  { code: "LK", label: "Sri Lanka", phone: "94" },
  { code: "LR", label: "Liberia", phone: "231" },
  { code: "LS", label: "Lesotho", phone: "266" },
  { code: "LT", label: "Lithuania", phone: "370" },
  { code: "LU", label: "Luxembourg", phone: "352" },
  { code: "LV", label: "Latvia", phone: "371" },
  { code: "LY", label: "Libya", phone: "218" },
  { code: "MA", label: "Morocco", phone: "212" },
  { code: "MC", label: "Monaco", phone: "377" },
  {
    code: "MD",
    label: "Moldova, Republic of",
    phone: "373",
  },
  { code: "ME", label: "Montenegro", phone: "382" },
  {
    code: "MF",
    label: "Saint Martin (French part)",
    phone: "590",
  },
  { code: "MG", label: "Madagascar", phone: "261" },
  { code: "MH", label: "Marshall Islands", phone: "692" },
  {
    code: "MK",
    label: "Macedonia, the Former Yugoslav Republic of",
    phone: "389",
  },
  { code: "ML", label: "Mali", phone: "223" },
  { code: "MM", label: "Myanmar", phone: "95" },
  { code: "MN", label: "Mongolia", phone: "976" },
  { code: "MO", label: "Macao", phone: "853" },
  {
    code: "MP",
    label: "Northern Mariana Islands",
    phone: "1-670",
  },
  { code: "MQ", label: "Martinique", phone: "596" },
  { code: "MR", label: "Mauritania", phone: "222" },
  { code: "MS", label: "Montserrat", phone: "1-664" },
  { code: "MT", label: "Malta", phone: "356" },
  { code: "MU", label: "Mauritius", phone: "230" },
  { code: "MV", label: "Maldives", phone: "960" },
  { code: "MW", label: "Malawi", phone: "265" },
  { code: "MX", label: "Mexico", phone: "52" },
  { code: "MY", label: "Malaysia", phone: "60" },
  { code: "MZ", label: "Mozambique", phone: "258" },
  { code: "NA", label: "Namibia", phone: "264" },
  { code: "NC", label: "New Caledonia", phone: "687" },
  { code: "NE", label: "Niger", phone: "227" },
  { code: "NF", label: "Norfolk Island", phone: "672" },
  { code: "NG", label: "Nigeria", phone: "234" },
  { code: "NI", label: "Nicaragua", phone: "505" },
  { code: "NL", label: "Netherlands", phone: "31" },
  { code: "NO", label: "Norway", phone: "47" },
  { code: "NP", label: "Nepal", phone: "977" },
  { code: "NR", label: "Nauru", phone: "674" },
  { code: "NU", label: "Niue", phone: "683" },
  { code: "NZ", label: "New Zealand", phone: "64" },
  { code: "OM", label: "Oman", phone: "968" },
  { code: "PA", label: "Panama", phone: "507" },
  { code: "PE", label: "Peru", phone: "51" },
  { code: "PF", label: "French Polynesia", phone: "689" },
  { code: "PG", label: "Papua New Guinea", phone: "675" },
  { code: "PH", label: "Philippines", phone: "63" },
  { code: "PK", label: "Pakistan", phone: "92" },
  { code: "PL", label: "Poland", phone: "48" },
  {
    code: "PM",
    label: "Saint Pierre and Miquelon",
    phone: "508",
  },
  { code: "PN", label: "Pitcairn", phone: "870" },
  { code: "PR", label: "Puerto Rico", phone: "1" },
  {
    code: "PS",
    label: "Palestine, State of",
    phone: "970",
  },
  { code: "PT", label: "Portugal", phone: "351" },
  { code: "PW", label: "Palau", phone: "680" },
  { code: "PY", label: "Paraguay", phone: "595" },
  { code: "QA", label: "Qatar", phone: "974" },
  { code: "RE", label: "Reunion", phone: "262" },
  { code: "RO", label: "Romania", phone: "40" },
  { code: "RS", label: "Serbia", phone: "381" },
  { code: "RU", label: "Russian Federation", phone: "7" },
  { code: "RW", label: "Rwanda", phone: "250" },
  { code: "SA", label: "Saudi Arabia", phone: "966" },
  { code: "SB", label: "Solomon Islands", phone: "677" },
  { code: "SC", label: "Seychelles", phone: "248" },
  { code: "SD", label: "Sudan", phone: "249" },
  { code: "SE", label: "Sweden", phone: "46" },
  { code: "SG", label: "Singapore", phone: "65" },
  { code: "SH", label: "Saint Helena", phone: "290" },
  { code: "SI", label: "Slovenia", phone: "386" },
  {
    code: "SJ",
    label: "Svalbard and Jan Mayen",
    phone: "47",
  },
  { code: "SK", label: "Slovakia", phone: "421" },
  { code: "SL", label: "Sierra Leone", phone: "232" },
  { code: "SM", label: "San Marino", phone: "378" },
  { code: "SN", label: "Senegal", phone: "221" },
  { code: "SO", label: "Somalia", phone: "252" },
  { code: "SR", label: "Suriname", phone: "597" },
  { code: "SS", label: "South Sudan", phone: "211" },
  {
    code: "ST",
    label: "Sao Tome and Principe",
    phone: "239",
  },
  { code: "SV", label: "El Salvador", phone: "503" },
  {
    code: "SX",
    label: "Sint Maarten (Dutch part)",
    phone: "1-721",
  },
  {
    code: "SY",
    label: "Syrian Arab Republic",
    phone: "963",
  },
  { code: "SZ", label: "Swaziland", phone: "268" },
  {
    code: "TC",
    label: "Turks and Caicos Islands",
    phone: "1-649",
  },
  { code: "TD", label: "Chad", phone: "235" },
  {
    code: "TF",
    label: "French Southern Territories",
    phone: "262",
  },
  { code: "TG", label: "Togo", phone: "228" },
  { code: "TH", label: "Thailand", phone: "66" },
  { code: "TJ", label: "Tajikistan", phone: "992" },
  { code: "TK", label: "Tokelau", phone: "690" },
  { code: "TL", label: "Timor-Leste", phone: "670" },
  { code: "TM", label: "Turkmenistan", phone: "993" },
  { code: "TN", label: "Tunisia", phone: "216" },
  { code: "TO", label: "Tonga", phone: "676" },
  { code: "TR", label: "Turkey", phone: "90" },
  {
    code: "TT",
    label: "Trinidad and Tobago",
    phone: "1-868",
  },
  { code: "TV", label: "Tuvalu", phone: "688" },
  {
    code: "TW",
    label: "Taiwan",
    phone: "886",
  },
  {
    code: "TZ",
    label: "United Republic of Tanzania",
    phone: "255",
  },
  { code: "UA", label: "Ukraine", phone: "380" },
  { code: "UG", label: "Uganda", phone: "256" },
  {
    code: "US",
    label: "United States",
    phone: "1",
    suggested: true,
  },
  { code: "UY", label: "Uruguay", phone: "598" },
  { code: "UZ", label: "Uzbekistan", phone: "998" },
  {
    code: "VA",
    label: "Holy See (Vatican City State)",
    phone: "379",
  },
  {
    code: "VC",
    label: "Saint Vincent and the Grenadines",
    phone: "1-784",
  },
  { code: "VE", label: "Venezuela", phone: "58" },
  {
    code: "VG",
    label: "British Virgin Islands",
    phone: "1-284",
  },
  {
    code: "VI",
    label: "US Virgin Islands",
    phone: "1-340",
  },
  { code: "VN", label: "Vietnam", phone: "84" },
  { code: "VU", label: "Vanuatu", phone: "678" },
  { code: "WF", label: "Wallis and Futuna", phone: "681" },
  { code: "WS", label: "Samoa", phone: "685" },
  { code: "XK", label: "Kosovo", phone: "383" },
  { code: "YE", label: "Yemen", phone: "967" },
  { code: "YT", label: "Mayotte", phone: "262" },
  { code: "ZA", label: "South Africa", phone: "27" },
  { code: "ZM", label: "Zambia", phone: "260" },
  { code: "ZW", label: "Zimbabwe", phone: "263" },
];

export const USERS = [
  {
    id: "1",
    name: "Angelique Morse",
    email: "benny89@yahoo.com",
    phoneNumber: "+46 8 123 456",
    company: "Wuckert Inc",
    // role: UserRole.MODERATOR,
    status: UserStatus.BANNED,
    avatar: "https://i.pravatar.cc/150?u=1",
    joinedAt: "2025-01-12",
    lastLogin: "2 min ago",
    grade: GRADE_OPTIONS[0].label,
  },
  {
    id: "2",
    name: "Ariana Lang",
    email: "avery43@hotmail.com",
    phoneNumber: "+54 11 1234-5678",
    company: "Feest Group",
    // role: UserRole.ADMIN,
    status: UserStatus.PENDING,
    avatar: "https://i.pravatar.cc/150?u=2",
    joinedAt: "2025-02-15",
    lastLogin: "1 hour ago",
    grade: GRADE_OPTIONS[1].label,
  },
  {
    id: "3",
    name: "Aspen Schmitt",
    email: "mireya13@hotmail.com",
    phoneNumber: "+34 91 123 4567",
    company: "Kihn, Marquardt and Crist",
    // role: UserRole.JUDGE,
    status: UserStatus.BANNED,
    avatar: "https://i.pravatar.cc/150?u=3",
    joinedAt: "2025-03-01",
    lastLogin: "3 hours ago",
    grade: GRADE_OPTIONS[2].label,
  },
  {
    id: "4",
    name: "Brycen Jimenez",
    email: "tyrel.greenholt@gmail.com",
    phoneNumber: "+52 55 1234 5678",
    company: "Rempel, Hand and Herzog",
    // role: UserRole.MODERATOR,
    status: UserStatus.ACTIVE,
    avatar: "https://i.pravatar.cc/150?u=4",
    joinedAt: "2025-01-20",
    lastLogin: "2 days ago",
    grade: GRADE_OPTIONS[4].label,
  },
  {
    id: "5",
    name: "Chase Day",
    email: "joana.simonis84@gmail.com",
    phoneNumber: "+86 10 1234 5678",
    company: "Mraz, Donnelly and Collins",
    // role: UserRole.PARTICIPANT,
    status: UserStatus.BANNED,
    avatar: "https://i.pravatar.cc/150?u=5",
    joinedAt: "2025-02-10",
    lastLogin: "1 week ago",
    grade: GRADE_OPTIONS[4].label,
  },
  {
    id: "6",
    name: "Chase Day",
    email: "joana.simonis84@gmail.com",
    phoneNumber: "+86 10 1234 5678",
    company: "Mraz, Donnelly and Collins",
    // role: UserRole.PARTICIPANT,
    status: UserStatus.BANNED,
    avatar: "https://i.pravatar.cc/150?u=5",
    joinedAt: "2025-02-10",
    lastLogin: "1 week ago",
    grade: GRADE_OPTIONS[4].label,
  },
];

export const JUDGES = [
  {
    id: "J1",
    name: "Dr. Sarah Miller",
    email: "s.miller@university.edu",
    phoneNumber: "+1 202-555-0123",
    expertise: "Artificial Intelligence",
    status: UserStatus.ACTIVE,
    avatar: "https://i.pravatar.cc/150?u=j1",
    joinedAt: "2024-05-10",
  },
  {
    id: "J2",
    name: "Mark Thompson",
    email: "mark.t@techcorp.com",
    phoneNumber: "+44 20 7946 0958",
    expertise: "Frontend Development",
    status: UserStatus.ACTIVE,
    avatar: "https://i.pravatar.cc/150?u=j2",
    joinedAt: "2024-06-15",
  },
  {
    id: "J3",
    name: "Elena Rodriguez",
    email: "elena.r@designhub.io",
    phoneNumber: "+34 912 345 678",
    expertise: "UI/UX Design",
    status: UserStatus.PENDING,
    avatar: "https://i.pravatar.cc/150?u=j3",
    joinedAt: "2024-08-20",
  },
];

export const CONTEST_TABLE_HEADER = [
  // "Id",
  "Contest Name",
  "Description",
  "Start Date",
  "End Date",
  "Status",
  "Entries",
  "Actions",
];

export const CONTEST_TABLE_STATUS = [
  {
    label: UserStatus.ALL,
  },
  {
    label: UserStatus.PUBLISHED,
  },
  {
    label: UserStatus.OFFLINE,
  },
];

export const EXPERTISE_OPTIONS = [
  "AI",
  "Machine Learning",
  "Data Science",
  "Web Development",
  "Mobile Development",
  "UI/UX Design",
  "Graphic Design",
  "Digital Marketing",
  "Content Writing",
  "Video Editing",
  "Photography",
  "Music",
  "Art",
  "Other",
];

export const USER_STATUS_TABS = [
  {
    label: UserStatus.ALL,
  },
  {
    label: UserStatus.ACTIVE,
  },
  {
    label: UserStatus.PENDING,
  },
  {
    label: UserStatus.BANNED,
  },
];

export const VOTING_PERIOD_TYPE_DATA = [
  {
    label: "Public Voting",
    value: VOTING_PERIOD_TYPE.PUBLIC_VOTING,
  },
  {
    label: "Judge Voting",
    value: VOTING_PERIOD_TYPE.JUDGE_VOTING,
  },
];
